version: '3.3'

services:
  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: confdb
      MYSQL_USER: aleksandr
      MYSQL_PASSWORD: alekspass
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - net
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: confdb
      MYSQL_USER: aleksandr
      MYSQL_PASSWORD: alekspass
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - net
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql
      
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "db-node-1"
      - "db-node-2"
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - net
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"

  cache:
    image: redis:6.2-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 5 1 --loglevel warning 
    volumes: 
      - cache:/data

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
        ZOOKEEPER_INIT_LIMIT: 5

  kafka-node-1:
      image: wurstmeister/kafka
      container_name: kafka-node-1
      depends_on:
          - zookeeper
      ports:
          - "2181:2181"
          - "9092:9092"
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_HOST_NAME: localhost
          ADVERTISED_PORT: 9092
          ADVERTISED_HOST_NAME: localhost
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:
  cache:
    driver: local

networks:
  net:
    driver: "bridge"
    external: false
